AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notes-app
Globals:
  Function:
    Timeout: 3
####################################### Define DynamoDB
Resources:
  NoteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: notes
      AttributeDefinitions:
        - AttributeName: item
          AttributeType: S
      KeySchema:
        - AttributeName: item
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
####################################### Define S3_Bucket
  MyFilesBucket:
    Type: AWS::S3::Bucket
####################################### Define Note_Lambda_Function
  NoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.app
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ServiceStatusAPI:
          Type: Api
          Properties:
            Path: /
            Method: get
####################################### Define Add_Note_Lambda_Function
  AddNoteFunction:
     Type: AWS::Serverless::Function
     Properties:
       CodeUri: src/
       Handler: add.add
       Runtime: python3.8
       Policies:
         - DynamoDBCrudPolicy:
             TableName:
               !Ref NoteTable
       Architectures:
         - x86_64
       Events:
         PostDataAPI:
           Type: Api
           Properties:
             Path: /
             Method: post
####################################### Define Query_Lambda_Function
  QueryFunction:
     Type: AWS::Serverless::Function
     Properties:
       CodeUri: src/
       Handler: query.query
       Runtime: python3.8
       Environment:
        Variables:
          BUCKET_NAME: !Ref MyFilesBucket
       Policies:
         - AmazonDynamoDBFullAccess
         - S3WritePolicy:
             BucketName: 
               !Ref MyFilesBucket
       Architectures:
         - x86_64
       Events:
        ReportGeneratorScheduler:
          Type: Schedule
          Properties:
            Schedule: rate(7 days)
####################################### Print Output
Outputs:
  ServiceApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"